CREATE EXTENSION vector;

CREATE TABLE image (
  hash VARCHAR(64) PRIMARY KEY,
  size INTEGER NOT NULL,
  format VARCHAR(10) NOT NULL,
  width INTEGER NOT NULL,
  height INTEGER NOT NULL,
  entropy DOUBLE PRECISION NOT NULL,
  transparent BOOLEAN NOT NULL,
  created_at TIMESTAMP NOT NULL,
  label TEXT DEFAULT NULL,
  dino_embedding VECTOR(1536) DEFAULT NULL,
  clip_embedding VECTOR(768) DEFAULT NULL
);
